# Generated by Django 3.0.6 on 2020-08-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200611_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alamat_lengkap',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nomor_telepon',
            field=models.CharField(max_length=20),
        ),
    ]
