# Generated by Django 3.0.6 on 2020-07-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200611_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='laboratorium_yang_dinilai',
        ),
    ]
