# Generated by Django 3.0.6 on 2020-07-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200717_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_1',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_10',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_11',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_12',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_13',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_14',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_15',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_16',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_17',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_18',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_19',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_2',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_20',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_21',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_22',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_23',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_24',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_25',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_26',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_27',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_28',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_29',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_3',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_30',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_31',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_32',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_33',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_34',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_35',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_36',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_37',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_38',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_39',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_4',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_40',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_41',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_42',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_43',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_44',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_45',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_46',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_47',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_48',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_49',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_5',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_50',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_51',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_52',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_53',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_54',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_6',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_7',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_8',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_9',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
    ]
