# Generated by Django 3.0.6 on 2020-07-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200728_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='keterangan_kebijakan_sistem_manajemen_biorisiko',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='keterangan_tujuan_dan_program_manajemen_biorisiko',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='nilai_no_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='nilai_no_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='rekomendasi_kebijakan_sistem_manajemen_biorisiko',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='rekomendasi_tujuan_dan_program_manajemen_biorisiko',
        ),
    ]
