# Generated by Django 3.0.6 on 2020-07-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200728_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_kebijakan_sistem_manajemen_biorisiko',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_1',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_kebijakan_sistem_manajemen_biorisiko',
            field=models.TextField(default='Isi Laporan'),
        ),
    ]
