# Generated by Django 3.0.6 on 2020-07-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200729_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='nilai_no_1',
        ),
    ]
