# Generated by Django 3.0.6 on 2020-07-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_questionnaire_nilai_no_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_1',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
    ]
