# Generated by Django 3.0.6 on 2020-07-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_questionnaire_nilai_no_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='nilai_no_1',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_1_0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_1_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_1_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_1_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_1_4',
            field=models.BooleanField(default=True),
        ),
    ]
