# Generated by Django 3.0.6 on 2020-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200729_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='nilai_no_1_0',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='nilai_no_1_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='nilai_no_1_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='nilai_no_1_3',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='nilai_no_1_4',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_1',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
    ]
