# Generated by Django 3.0.6 on 2020-07-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200729_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='nilai_no_1',
        ),
    ]
