# Generated by Django 3.0.6 on 2020-07-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_questionnaire_nilai_no_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_1',
            field=models.IntegerField(),
        ),
    ]
