# Generated by Django 3.0.6 on 2020-07-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200729_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_1',
            field=models.IntegerField(default=4),
        ),
    ]
