# Generated by Django 3.0.6 on 2020-07-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20200730_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_tujuan_dan_program_manajemen_biorisiko',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_tujuan_dan_program_manajemen_biorisiko',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_1',
            field=models.IntegerField(default=0),
        ),
    ]
