# Generated by Django 3.0.6 on 2020-07-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20200730_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_inspeksi_dan_audit',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_komunikasi_dan_konsultasi',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_kontraktor_dan_suplier_purchasing',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_pencatatan_dokumen_dan_pengendalian_dokumen',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_pengembangan_berkelanjutan',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_pengendalian_ketidaksesuaian_dan_perbaikan',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_perencanaan_dan_program_kerja',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_persyaratan_legal_aturan_atau_izin',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_perubahan_terkait_manajemen_biorisiko',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_review_dan_perbaikan_manajemen_biorisiko',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_tanggung_jawab_dan_wewenang',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nilai_no_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_inspeksi_dan_audit',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_komunikasi_dan_konsultasi',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_kontraktor_dan_suplier_purchasing',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_pencatatan_dokumen_dan_pengendalian_dokumen',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_pengembangan_berkelanjutan',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_pengendalian_ketidaksesuaian_dan_perbaikan',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_perencanaan_dan_program_kerja',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_persyaratan_legal_aturan_atau_izin',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_perubahan_terkait_manajemen_biorisiko',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_review_dan_perbaikan_manajemen_biorisiko',
            field=models.TextField(default='Isi Laporan'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_tanggung_jawab_dan_wewenang',
            field=models.TextField(default='Isi Laporan'),
        ),
    ]
