# Generated by Django 3.0.6 on 2020-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20200802_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_dekontaminasi_dan_disinfeksi_peralatan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_identifikasi_perencanaan_dan_respon_keadaan_darurat',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_inaktivasi_bahan_biologik_dan_bahan_berbahaya_lainnya',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_infrastruktur_dan_operasional',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_inventarisasi_informasi_dan_pencatatan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_investigasi_kecelakaan_dan_insiden',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_keamanan_fisik_dan_pengendalian_personel',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_kebijakan_sistem_manajemen_biorisiko',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_ketersediaan_peralatan_keselamatan_untuk_tanggap_darurat',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_komunikasi_dan_konsultasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_kontraktor_dan_suplier_purchasing',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_pemeliharaan_dan_dekontaminasi_reusable_apd',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_pencatatan_dokumen_dan_pengendalian_dokumen',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_pengadaan_alat_pelindung_diri',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_pengembangan_berkelanjutan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_pengendalian_dan_monitoring',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_pengendalian_ketidaksesuaian_dan_perbaikan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_pengolahan_limbah_dan_bahan_berbahaya_biologi_kimia',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_penyimpanan_bahan_biologik_dan_bahan_berbahaya_lainnya',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_peran_dan_tanggung_jawab',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_perencanaan_dan_program_kerja',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_perencanaan_desain_dan_verifikasi_mencakup_commissioning_dan_decommisioning',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_persyaratan_legal_aturan_atau_izin',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_perubahan_terkait_manajemen_biorisiko',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_program_kesehatan_kerja',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_prosedur_penerimaan_dan_pengiriman_bahan_biologik_dan_bahan_berbahaya_lainnya',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_proses_metode_dan_prosedur',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_rekrutmen_pelatihan_dan_kompetensi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_rencana_tanggap_darurat_menghadapi_kejadian_luar_duga',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_review_dan_perbaikan_manajemen_biorisiko',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_ruang_lingkup_dan_penjadwalan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_simulasi_dan_pelatihan_tanggap_darurat',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_tanggung_jawab_dan_wewenang',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_transfer_bahan_biologik_dan_bahan_berbahaya_lainnya',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_tujuan_dan_program_manajemen_biorisiko',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_14',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_15',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_16',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_17',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_18',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_19',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_20',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_21',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_22',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_23',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_24',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_25',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_26',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_27',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_28',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_29',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_30',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_31',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_32',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_33',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_34',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_35',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_36',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_37',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_38',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_39',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_40',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_41',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_42',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_43',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_44',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_45',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_46',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_47',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_48',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_49',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_50',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_51',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_52',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_53',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_54',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_dekontaminasi_dan_disinfeksi_peralatan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_identifikasi_perencanaan_dan_respon_keadaan_darurat',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_inaktivasi_bahan_biologik_dan_bahan_berbahaya_lainnya',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_infrastruktur_dan_operasional',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_inventarisasi_informasi_dan_pencatatan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_investigasi_kecelakaan_dan_insiden',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_keamanan_fisik_dan_pengendalian_personel',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_kebijakan_sistem_manajemen_biorisiko',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_ketersediaan_peralatan_keselamatan_untuk_tanggap_darurat',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_komunikasi_dan_konsultasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_kontraktor_dan_suplier_purchasing',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_manajemen_pemeliharaan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_pemeliharaan_dan_dekontaminasi_reusable_apd',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_pencatatan_dokumen_dan_pengendalian_dokumen',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_pengadaan_alat_pelindung_diri',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_pengembangan_berkelanjutan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_pengendalian_dan_monitoring',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_pengendalian_ketidaksesuaian_dan_perbaikan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_pengolahan_limbah_dan_bahan_berbahaya_biologi_kimia',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_penyimpanan_bahan_biologik_dan_bahan_berbahaya_lainnya',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_peran_dan_tanggung_jawab',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_perencanaan_dan_program_kerja',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_perencanaan_desain_dan_verifikasi_mencakup_commissioning_dan_decommisioning',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_persyaratan_legal_aturan_atau_izin',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_perubahan_terkait_manajemen_biorisiko',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_program_kesehatan_kerja',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_prosedur_penerimaan_dan_pengiriman_bahan_biologik_dan_bahan_berbahaya_lainnya',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_proses_metode_dan_prosedur',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_rekrutmen_pelatihan_dan_kompetensi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_rencana_tanggap_darurat_menghadapi_kejadian_luar_duga',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_review_dan_perbaikan_manajemen_biorisiko',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_ruang_lingkup_dan_penjadwalan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_simulasi_dan_pelatihan_tanggap_darurat',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_tanggung_jawab_dan_wewenang',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_transfer_bahan_biologik_dan_bahan_berbahaya_lainnya',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_tujuan_dan_program_manajemen_biorisiko',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
    ]
