# Generated by Django 3.0.6 on 2020-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200802_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_APD_personel',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_GMT_peralatan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_GMT_personel',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_general_safety',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_identifikasi_hazard',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_inspeksi_dan_audit',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_kalibrasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_keamanan_informasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_kedaruratan_medik',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_latar_belakang_sdm',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_manajemen_pemeliharaan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_monitoring_peralatan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_pelabelan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_pengendalian_personel',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_pengendalian_risiko',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_sertifikasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_suksesi_dan_eksklusi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_vaksinasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='keterangan_validasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_10',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_11',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_12',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_13',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_14',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_15',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_16',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_17',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_18',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_19',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_20',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_21',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_22',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_23',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_24',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_25',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_26',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_27',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_28',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_29',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_30',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_31',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_32',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_33',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_34',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_35',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_36',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_37',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_38',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_39',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_40',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_41',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_42',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_43',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_44',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_45',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_46',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_47',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_48',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_49',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_50',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_51',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_52',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_53',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_54',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nilai_no_9',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_APD_personel',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_GMT_peralatan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_GMT_personel',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_general_safety',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_identifikasi_hazard',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_inspeksi_dan_audit',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_kalibrasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_keamanan_informasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_kedaruratan_medik',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_latar_belakang_sdm',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_monitoring_peralatan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_pelabelan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_pengendalian_personel',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_pengendalian_risiko',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_sertifikasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_suksesi_dan_eksklusi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_vaksinasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rekomendasi_validasi',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
    ]
