# Generated by Django 3.0.7 on 2020-08-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20200802_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='full_name',
            new_name='nama_lengkap',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='message',
            new_name='pesan',
        ),
        migrations.AddField(
            model_name='contactus',
            name='alamat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
