# Generated by Django 3.0.7 on 2020-09-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20200830_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='catatan_utama',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='kekuatan_utama',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='kelemahan_utama',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='kesimpulan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='komentar',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='saran_untuk_perbaikan',
            field=models.TextField(blank=True, default='Isi Laporan', null=True),
        ),
    ]
