# Generated by Django 3.0.7 on 2020-09-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20200901_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
