# Generated by Django 3.0.7 on 2020-09-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20200901_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
