# Generated by Django 3.0.7 on 2020-09-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20200901_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='catatan_utama',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='kesimpulan',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='komentar',
        ),
    ]
