# Generated by Django 3.0.7 on 2020-09-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20200902_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan_1', models.IntegerField(null=True)),
                ('pilihan_2', models.IntegerField(null=True)),
            ],
        ),
    ]
